# Shared Gitlab Config
# https://gitlab.youngsolutions.ch/devops/gitlab/shared-ci-config

stages:
  - build
  - release

include:
  - project: 'devops/gitlab/shared-ci-config'
    ref: master
    file: '.gitlab-ci/docker-only.yml'
